<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CourseRegistrationManagmentSystem.Business\CourseRegistrationManagmentSystem.Business.csproj" />
    <ProjectReference Include="..\CourseRegistrationManagmentSystem.Data\CourseRegistrationManagmentSystem.Data.csproj" />
    <ProjectReference Include="..\CourseRegistrationManagmentSystem.Shared\CourseRegistrationManagmentSystem.Shared.csproj" />
  </ItemGroup>

</Project>
