<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mozaic.CourseRegistrationManagementSystem.BL\Mozaic.CourseRegistrationManagementSystem.BL.csproj" />
    <ProjectReference Include="..\Mozaic.CourseRegistrationManagementSystem.DAL\Mozaic.CourseRegistrationManagementSystem.DAL.csproj" />
    <ProjectReference Include="..\Mozaic.CourseRegistrationManagementSystem.Shared\Mozaic.CourseRegistrationManagementSystem.Shared.csproj" />
  </ItemGroup>

</Project>
